name: nemos
channels:
  - conda-forge
  - nvidia
dependencies:
  - ffmpeg
  - pip
  - cudatoolkit
  - cudnn
  - python=3.10
  - cuda-python
  - jax
  - cuda-nvcc
  - pip:
      - git+https://github.com/flatironinstitute/nemos-workshop-feb-2024.git@binder
