#!/bin/bash

conda activate nemos
cd nemos-workshop-feb-2024/
python scripts/strip_text.py
python src/workshop_utils/data.py ../data/
mkdocs build
cd ..
mkdir -p notebooks/
cp nemos-workshop-feb-2024/site/generated/for_users/*ipynb notebooks/
